### ISSUE TITLE
Identifier not found "TCustomAttribute"

### ISSUE THREAD

**Issue by tomlin7** [mr-highball/ezjson#1]
I tried to copy code from the test project,
```
Compile Project, Target: testing.exe: Exit code 1, Errors: 2
ezjson.pas(41,27) Error: Identifier not found "TCustomAttribute"
ezjson.pas(41,43) Error: class type expected, but got "<erroneous type>"
```
![image](https://user-images.githubusercontent.com/70792552/110232778-cb7eeb00-7f17-11eb-8328-a348c6b7d38e.png)

also when I tried to run the original test project, it shows there is no main script set
![image](https://user-images.githubusercontent.com/70792552/110232848-3c260780-7f18-11eb-9c99-9a8b1494af9d.png)

**Comment by mr-highball** [comment]
Hello @billyeatcookies 
Custom attributes are a "trunk" feature and won't be in a main release until version 3.4
https://foundation.freepascal.org/projects/project-3 

If you get trunk fpc/lazarus then you would be able to open the test project and compile tests. There's still some quirks with ny implementation that I need to iron out as well but for most simple cases ezjson should be able to handle the serialization / deserialization

**Comment by mr-highball** [comment]
I'd also like to point out that if you haven't used fpcupdeluxe before it makes setting up trunk (as well as cross compilers) very easy.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe

**Comment by tomlin7** [comment]
thank you for replying, i tried to install a trunk version using fpcupdeluxe, well that didn't work for me.
keep the project updated and active :)

**Comment by mr-highball** [comment]
Will do. Probably will pick it back up to "finish up" sooner rather than later.
